-- Expand board catalog with many more granular categories (idempotent upsert)

insert into public.board_catalog (name, group_name, sort_order) values
  -- Sports (expanded)
  ('Athletics', 'Sports', 25),
  ('Running', 'Sports', 26),
  ('Marathon', 'Sports', 27),
  ('Triathlon', 'Sports', 28),
  ('Surfing', 'Sports', 29),
  ('Skateboarding', 'Sports', 30),
  ('Rock Climbing', 'Sports', 31),
  ('Wrestling', 'Sports', 32),
  ('American Football', 'Sports', 33),
  ('Badminton', 'Sports', 34),
  ('Table Tennis', 'Sports', 35),
  ('Handball', 'Sports', 36),
  ('Lacrosse', 'Sports', 37),
  ('Pickleball', 'Sports', 38),
  ('Padel', 'Sports', 39),
  ('Squash', 'Sports', 40),
  ('Fencing', 'Sports', 41),
  ('Gymnastics', 'Sports', 42),
  ('Figure Skating', 'Sports', 43),
  ('Motorsport', 'Sports', 44),
  ('Rally', 'Sports', 45),
  ('NASCAR', 'Sports', 46),
  ('Darts', 'Sports', 47),
  ('Snooker', 'Sports', 48),
  ('Rowing', 'Sports', 49),
  ('Sailing', 'Sports', 50),
  ('Horse Racing', 'Sports', 51),
  ('Equestrian', 'Sports', 52),
  ('Esports', 'Sports', 53),
  ('CrossFit', 'Sports', 54),
  ('Bodybuilding', 'Sports', 55),
  ('Powerlifting', 'Sports', 56),
  ('Trail Running', 'Sports', 57),
  ('Mountain Biking', 'Sports', 58),
  ('Parkour', 'Sports', 59),
  ('Chess', 'Sports', 60),
  ('Poker', 'Sports', 61),

  -- Music (expanded)
  ('Indie', 'Music', 70),
  ('Metal', 'Music', 71),
  ('Punk', 'Music', 72),
  ('Blues', 'Music', 73),
  ('Soul', 'Music', 74),
  ('Disco', 'Music', 75),
  ('Funk', 'Music', 76),
  ('Country', 'Music', 77),
  ('Reggae', 'Music', 78),
  ('Reggaeton', 'Music', 79),
  ('K-Pop', 'Music', 80),
  ('J-Pop', 'Music', 81),
  ('Afrobeats', 'Music', 82),
  ('Ambient', 'Music', 83),
  ('Lo-Fi', 'Music', 84),
  ('Soundtrack', 'Music', 85),
  ('Gospel', 'Music', 86),
  ('Grime', 'Music', 87),
  ('Drill', 'Music', 88),
  ('Trap', 'Music', 89),
  ('DnB', 'Music', 90),
  ('Trance', 'Music', 91),
  ('Dubstep', 'Music', 92),
  ('Synthwave', 'Music', 93),
  ('Alternative', 'Music', 94),
  ('Grunge', 'Music', 95),
  ('Opera', 'Music', 96),
  ('Musical Theatre', 'Music', 97),
  ('DJ Mixes', 'Music', 98),
  ('Live Music', 'Music', 99),
  ('Music Production', 'Music', 100),
  ('Vinyl', 'Music', 101),

  -- Lifestyle (expanded)
  ('Parenting', 'Lifestyle', 120),
  ('Pets', 'Lifestyle', 121),
  ('Gardening', 'Lifestyle', 122),
  ('Interior Design', 'Lifestyle', 123),
  ('Real Estate', 'Lifestyle', 124),
  ('Cars', 'Lifestyle', 125),
  ('Motorcycles', 'Lifestyle', 126),
  ('Watches', 'Lifestyle', 127),
  ('Jewelry', 'Lifestyle', 128),
  ('Sneakers', 'Lifestyle', 129),
  ('Streetwear', 'Lifestyle', 130),
  ('Wellness', 'Lifestyle', 131),
  ('Meditation', 'Lifestyle', 132),
  ('Nutrition', 'Lifestyle', 133),
  ('Skincare', 'Lifestyle', 134),
  ('Makeup', 'Lifestyle', 135),
  ('Hair', 'Lifestyle', 136),
  ('Weddings', 'Lifestyle', 137),
  ('Dating', 'Lifestyle', 138),
  ('Sustainability', 'Lifestyle', 139),
  ('Outdoors', 'Lifestyle', 140),
  ('Camping', 'Lifestyle', 141),
  ('Hiking', 'Lifestyle', 142),
  ('Luxury', 'Lifestyle', 143),
  ('Thrift', 'Lifestyle', 144),
  ('Vintage', 'Lifestyle', 145),
  ('Minimalism', 'Lifestyle', 146),
  ('Organization', 'Lifestyle', 147),
  ('Productivity', 'Lifestyle', 148),
  ('Self-Improvement', 'Lifestyle', 149),
  ('Spirituality', 'Lifestyle', 150),
  ('Yoga', 'Lifestyle', 151),
  ('Pilates', 'Lifestyle', 152),

  -- Food & Drink
  ('Baking', 'Food & Drink', 170),
  ('Desserts', 'Food & Drink', 171),
  ('Restaurants', 'Food & Drink', 172),
  ('Food Reviews', 'Food & Drink', 173),
  ('Meal Prep', 'Food & Drink', 174),
  ('Vegan', 'Food & Drink', 175),
  ('Vegetarian', 'Food & Drink', 176),
  ('Wine', 'Food & Drink', 177),
  ('Coffee', 'Food & Drink', 178),
  ('Cocktails', 'Food & Drink', 179),
  ('Beer', 'Food & Drink', 180),
  ('Street Food', 'Food & Drink', 181),
  ('Fine Dining', 'Food & Drink', 182),
  ('BBQ', 'Food & Drink', 183),
  ('Asian Cuisine', 'Food & Drink', 184),
  ('Italian Cuisine', 'Food & Drink', 185),
  ('Mexican Cuisine', 'Food & Drink', 186),
  ('Healthy Eating', 'Food & Drink', 187),

  -- Tech
  ('AI', 'Tech', 200),
  ('Machine Learning', 'Tech', 201),
  ('Web3', 'Tech', 202),
  ('Crypto', 'Tech', 203),
  ('Gadgets', 'Tech', 204),
  ('Mobile', 'Tech', 205),
  ('Hardware', 'Tech', 206),
  ('Cybersecurity', 'Tech', 207),
  ('DevOps', 'Tech', 208),
  ('Data Science', 'Tech', 209),
  ('Cloud', 'Tech', 210),
  ('Open Source', 'Tech', 211),
  ('Startups', 'Tech', 212),
  ('SaaS', 'Tech', 213),
  ('No-Code', 'Tech', 214),
  ('Automation', 'Tech', 215),
  ('Robotics', 'Tech', 216),
  ('3D Printing', 'Tech', 217),
  ('Apple', 'Tech', 218),
  ('Android', 'Tech', 219),

  -- Content & Learning
  ('Photography', 'Content', 240),
  ('Videography', 'Content', 241),
  ('Podcasts', 'Content', 242),
  ('YouTube', 'Content', 243),
  ('Streaming', 'Content', 244),
  ('TV Series', 'Content', 245),
  ('Anime', 'Content', 246),
  ('Comics', 'Content', 247),
  ('Manga', 'Content', 248),
  ('Memes', 'Content', 249),
  ('Social Media', 'Content', 250),
  ('Education', 'Content', 251),
  ('Languages', 'Content', 252),
  ('History', 'Content', 253),
  ('Philosophy', 'Content', 254),
  ('Psychology', 'Content', 255),
  ('Math', 'Content', 256),
  ('Physics', 'Content', 257),
  ('Biology', 'Content', 258),
  ('Space', 'Content', 259),
  ('Climate', 'Content', 260),
  ('Politics', 'Content', 261),
  ('Economics', 'Content', 262),
  ('Career', 'Content', 263),
  ('Writing', 'Content', 264),
  ('Journalism', 'Content', 265),
  ('Architecture', 'Content', 266),
  ('DIY', 'Content', 267),
  ('Crafts', 'Content', 268),
  ('Woodworking', 'Content', 269),
  ('Sewing', 'Content', 270),
  ('Documentaries', 'Content', 271),
  ('Stand-Up Comedy', 'Content', 272),
  ('Theatre', 'Content', 273),
  ('Dance', 'Content', 274),
  ('Poetry', 'Content', 275),
  ('Literature', 'Content', 276),
  ('True Crime', 'Content', 277),
  ('Interviews', 'Content', 278),
  ('Tutorials', 'Content', 279),

  -- Finance
  ('Investing', 'Finance', 300),
  ('Personal Finance', 'Finance', 301),
  ('Real Estate Investing', 'Finance', 302),
  ('Stock Market', 'Finance', 303),
  ('Budgeting', 'Finance', 304),
  ('Side Hustles', 'Finance', 305),
  ('Freelancing', 'Finance', 306),
  ('Entrepreneurship', 'Finance', 307),
  ('Marketing', 'Finance', 308),
  ('Sales', 'Finance', 309),
  ('Leadership', 'Finance', 310),
  ('Remote Work', 'Finance', 311),

  -- Entertainment & Gaming
  ('Board Games', 'Entertainment', 320),
  ('Card Games', 'Entertainment', 321),
  ('Mobile Games', 'Entertainment', 322),
  ('PC Gaming', 'Entertainment', 323),
  ('Console Gaming', 'Entertainment', 324),
  ('Retro Gaming', 'Entertainment', 325),
  ('Game Dev', 'Entertainment', 326),
  ('Movies', 'Entertainment', 327),
  ('Horror', 'Entertainment', 328),
  ('Sci-Fi', 'Entertainment', 329),
  ('Fantasy', 'Entertainment', 330),
  ('K-Drama', 'Entertainment', 331),
  ('Reality TV', 'Entertainment', 332),
  ('Sports Highlights', 'Entertainment', 333),
  ('Highlights', 'Entertainment', 334),
  ('Events', 'Entertainment', 335),
  ('Festivals', 'Entertainment', 336),
  ('Concerts', 'Entertainment', 337),
  ('Museums', 'Entertainment', 338),
  ('Exhibitions', 'Entertainment', 339)
on conflict (name) do update set
  group_name = excluded.group_name,
  sort_order = excluded.sort_order,
  active = true;
